vich_uploader:
    db_driver: orm

    metadata:
        type : attribute

    mappings:
        avatar:
            uri_prefix: /avatar/avatar
            upload_destination: '%kernel.project_dir%/public/avatar/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
