<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6w7gRIb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6w7gRIb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6w7gRIb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6w7gRIb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6w7gRIb\App_KernelDevDebugContainer([
    'container.build_hash' => '6w7gRIb',
    'container.build_id' => 'ac91970e',
    'container.build_time' => 1668507365,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6w7gRIb');
