<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVl9PrPv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVl9PrPv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVl9PrPv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVl9PrPv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVl9PrPv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vl9PrPv',
    'container.build_id' => '53cefd6b',
    'container.build_time' => 1668414299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVl9PrPv');
