<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2i2KA2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2i2KA2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2i2KA2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2i2KA2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2i2KA2\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2i2KA2',
    'container.build_id' => '0c7fdc0e',
    'container.build_time' => 1668436323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2i2KA2');
